export const NAVIGATION = {
  LOGIN: 'LOGIN',
  HOME: {
    MAIN: 'MAIN',
    EXPLORER: {
      EXPERTS: 'EXPERTS',
      SERVICES: 'SERVICES',
    },
    PROFILE: 'PROFILE',
  },
};

export const ACTIONS_MAIN = {
  LOGIN: 'LOGIN',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_REQUEST_FAILED: 'LOGIN_REQUEST_FAILED',
  LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  GET_EXPERTS: 'GET_EXPERTS',
  GET_EXPERTS_SUCCESS: 'GET_EXPERTS_SUCCESS',
  GET_EXPERTS_FAILED: 'GET_EXPERTS_FAILED',
  GET_SERVICES: 'GET_SERVICES',
  GET_SERVICES_SUCCESS: 'GET_SERVICES_SUCCESS',
  GET_SERVICES_FAILED: 'GET_SERVICES_FAILED',
};
